# Generated by Django 6.1.1 on 2026-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='photo',
            field=models.ImageField(blank=True, default='defaults/no-profile-picture-icon.png', null=True, upload_to='Instructor/photos'),
        ),
    ]
