# Generated by Django 6.1.1 on 2026-09-27 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_instructorprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='defaults/no-profile-picture-icon.png', null=True, upload_to='Instructor/photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
