# Generated by Django 6.1.1 on 2026-10-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_bio_studentprofile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediaaccounts',
            old_name='user',
            new_name='instructor_profile',
        ),
    ]
