# Generated by Django 6.1.1 on 2026-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_user_socialmediaaccounts_instructor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Instructor/photos'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Instructor/photos'),
        ),
    ]
