# Generated by Django 6.1.1 on 2026-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('DF', 'Draft')], default='AV', max_length=2),
        ),
    ]
