# Generated by Django 6.1.1 on 2026-09-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
