# Generated by Django 6.1.1 on 2026-10-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_module_slug_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
