# Generated by Django 6.1.1 on 2026-10-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_module_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
    ]
