# Generated by Django 6.1.1 on 2026-10-06 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_enrollments(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Enrollment = apps.get_model('courses', 'Enrollment')
    database = schema_editor.connection.alias
    students_through = Course.students.through

    Enrollment.objects.using(database).bulk_create(
        (
            Enrollment(course_id=course_id, user_id=user_id)
            for course_id, user_id in students_through.objects.using(database).values_list(
                'course_id', 'user_id'
            )
        ),
        ignore_conflicts=True,
    )


def restore_existing_enrollments(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Enrollment = apps.get_model('courses', 'Enrollment')
    database = schema_editor.connection.alias
    students_through = Course.students.through

    students_through.objects.using(database).bulk_create(
        (
            students_through(course_id=course_id, user_id=user_id)
            for course_id, user_id in Enrollment.objects.using(database).values_list(
                'course_id', 'user_id'
            )
        ),
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_module_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_enrolled', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_enrolled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(
            copy_existing_enrollments,
            restore_existing_enrollments,
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='courses.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_completed_modules', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_user_content_progress'),
        ),
    ]
